#!/usr/bin/env bash


## Global settings
# image name
DOCKER_IMAGE="${DOCKER_REPO:-smtp-relay}"


## Initialization
set -e

image_version=`cat VERSION`
image_name=`cat ${PWD}/_image`
image_tags=`cat ${PWD}/_tags`
image_building_name=`cat ${PWD}/_image_build`


## Enforce versioning
for tag in $image_tags; do
  if echo "$tag" | grep -q "$image_version"; then
    if curl -s 'https://hub.docker.com/v2/repositories/turgon37/smtp-relay/tags/?page_size=100' | grep -q '"name": "'${tag}'"'; then
      echo "ERROR: Tag '${tag}' for image version '$image_version' already exists in registry"
      exit 1
    fi
  fi
done

## Push images
for tag in $image_tags; do
  echo "=> tag image '${image_building_name}' as '${image_name}:${tag}'"
  docker tag "${image_building_name}" "${image_name}:${tag}"
  echo "=> push image '${image_name}:${tag}'"
  docker push "${image_name}:${tag}"
done
